### ISSUE TITLE
팀원 추천 수정사항

### ISSUE THREAD

**Issue by seheon99** [Team-Crops/fit-web#116]
- [x] 스크롤 빨리하면 API를 여러번 호출함 #120 
- [x] `username` 에서 `nickname` 으로 수정하기 #120 
- [x] 좋아요 눌렀을 때 `like: boolean` 상태 반대로 보냄 #120
